name: PY

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the pip
      run: pip install pytest
    
    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests.
      run pytest -q

deploy:
  needs: tests
  runs-on: ubuntu latest

  steps:
    - name: Checkout repo
      uses: action/checkout@v4

    - name: Build Docker image
      run: docker build -t myapp:latest

    - name: Save Docker image to tar
      run: docker save myapp:latest -o myapp.tar

    - name: Fix premissions
      run: sudo chmod 644 myapp.tar

    - name: Copy image to server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{136780.landvps.online}} 
        username: ${{root}}
        password: ${{3s0TLNUcmiM}}
        port: ${{94.159.112.56}} 
        source: "myapp.tar"
        target: "~/deploy"

    - name: Deploy on server via SSH
      uses: appleboy/ssh-action@v1
      with:
        host: ${{136780.landvps.online}} 
        username: ${{root}}
        password: ${{53s0TLNUcmiM}}
        port: ${{94.159.112.56}} 
        script: |
          mkdir -p ~/deploy
          cd ~/deploy

          echo "Loading Docker image..."
          docker load -i myapp.tar

          echo "Stopping old container..."
          docker rm -f myapp || true

          echo "Starting new container..."
          docker run -d --name myapp -p 80:80 myapp:latest

          echo "Depployment finished"  
